x-restart-policy: &restart_policy
  restart: unless-stopped

x-postgres: &db-postgres-settings
  image: postgres:15.6-alpine
  <<: *restart_policy
  expose:
    - 5432
  env_file:
    - .env
  environment:
    PGDATA: /home/postgres/data/pgdata
    POSTGRES_DB: ${DB_DATABASE:-database}
    POSTGRES_USER: ${DB_USERNAME:-admin}
    POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}

x-db-connection: &db-connection-setting
  DB_CONNECTION: ${DB_CONNECTION:-pgsql}
  DB_HOST: ${DB_HOST:-database}
  DB_PORT: ${DB_PORT:-5432}
  DB_DATABASE: ${DB_DATABASE:-database}
  DB_USERNAME: ${DB_USERNAME:-admin}
  DB_PASSWORD: ${DB_PASSWORD:-secret}

services:
  web:
    image: nginx:1.21-alpine
    working_dir: /etc/nginx
    <<: *restart_policy
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - .web/config/:/etc/nginx/conf.d
      - ./backend:/backend
    links:
      - backend

  backend:
    build:
      context: .backend/config
      dockerfile: Dockerfile
    expose:
      - 9000
    <<: *restart_policy
    working_dir: /backend
    user: docker
    volumes:
      - ./backend:/backend
      - .backend/extra/history:/home/docker/.history
    links:
      - database
    environment:
      HISTFILE: /home/docker/.history
      <<: *db-connection-setting

  worker:
    build:
      context: .backend/config
      dockerfile: Dockerfile
    <<: *restart_policy
    command: bash -c "php artisan queue:work"
    working_dir: /backend
    tty: true
    volumes:
      - ./backend:/backend
    links:
      - database
    environment:
      <<: *db-connection-setting

  database:
    <<: *db-postgres-settings
    volumes:
      - adnanAhmadiDB:/home/postgres/data:rw

  database_testing:
    <<: *db-postgres-settings
    tmpfs:
      - /home/postgres/data

  adminer:
    image: adminer:4.8.1
    <<: *restart_policy
    ports:
      - "${ADMINER_PORT:-8080}:8080"

volumes:
  adnanAhmadiDB:
    driver: local